default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: Warmup_development
  username: Warmup_development
  password: Warmup_development

test:
  <<: *default
  database: Warmup_test
  username: Warmup_test
  password: Warmup_test

production:
  <<: *default
  database: Warmup_production
  username: Warmup
  password: <%= ENV['WARMUP_DATABASE_PASSWORD'] %>
